version: "2"

run:
  timeout: 5m
  tests: true
  go: '1.25.5'

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unused

linters-settings:
  govet:
    disable:
      - fieldalignment

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck