# Version 2 configuration
version: 2

project_name: prometheus-storagebox-exporter

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: prometheus-storagebox-exporter
    main: .
    binary: prometheus-storagebox-exporter
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
    ldflags:
      - -s -w
      - -X main.Version={{ .Version }}
      - -X main.GitCommit={{ .FullCommit }}
      - -X main.BuildDate={{ .Date }}

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - DESIGN.md
      - grafana-provisioning/dashboards/grafana-dashboard.json

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - '^build:'
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Performance Improvements
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999

release:
  github:
    owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
    name: prometheus-storagebox-exporter
  draft: false
  prerelease: auto
  mode: replace
  name_template: "{{.ProjectName}} {{.Version}}"
  header: |
    ## Prometheus Hetzner Storage Box Exporter {{.Version}}

    ### 📦 Installation

    **Binary Download:**
    Download the appropriate binary for your platform from the assets below.

    **Docker:**
    Build and run using the included Dockerfile:
    ```bash
    # Build the image
    docker build -t prometheus-storagebox-exporter:{{.Version}} .

    # Or pull from GitHub Container Registry
    docker pull ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:{{.Version}}
    docker pull ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:latest

    # Run the container
    docker run -d \
      --name storagebox-exporter \
      -p 9509:9509 \
      -e HETZNER_TOKEN="your-api-token" \
      prometheus-storagebox-exporter:{{.Version}}
    ```

    ### 🔧 Configuration

    **Basic usage:**
    ```bash
    export HETZNER_TOKEN="your-api-token"
    ./prometheus-storagebox-exporter
    ```

    **With file-based token:**
    ```bash
    echo "your-api-token" > /run/secrets/hetzner-token
    export HETZNER_TOKEN_FILE="/run/secrets/hetzner-token"
    ./prometheus-storagebox-exporter
    ```

    ### 📚 Documentation

    - [Full Documentation](https://github.com/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}/blob/main/README.md)
    - [Configuration Guide](https://github.com/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}/blob/main/Claude.md)

    **Full Changelog**: https://github.com/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}/compare/{{ .PreviousTag }}...{{ .Tag }}
